#!/bin/sh
set -eu
# Alpha OS live-build config (Debian bookworm)
# IMPORTANT: use 'noauto' to avoid recursion. 'lb config' automatically calls this file.
lb config noauto \
  --distribution bookworm \
  --architectures amd64 \
  --archive-areas "main contrib non-free non-free-firmware" \
  --mirror-bootstrap http://deb.debian.org/debian/ \
  --mirror-chroot http://deb.debian.org/debian/ \
  --mirror-chroot-security http://security.debian.org/debian-security \
  --mirror-binary http://deb.debian.org/debian/ \
  --binary-images iso-hybrid \
  --debian-installer false \
  --apt-recommends false \
  --bootappend-live "persistence locales=en_US.UTF-8 timezone=UTC keyboard-layouts=us" \
  "${@}"
